spring:
  application:
    name: server-sentinel
  cloud:
    nacos:
      discovery:
        server-addr: 10.168.1.10:8848

feign:
  hystrix:
    enabled: true

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  ignored-services: '*'
  routes:
    provider:
      path: /provider/**
      serviceId: nacos-provider

# Hystrix默认的超时时间是1秒，如果超过这个时间未响应，将会进入fallback代码
hystrix:
  command:
    default:
      execution:
        strategy: THREAD
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 300000

ribbon:
  ReadTimeout: 60000 # 请求处理的超时时间
  ConnectTimeout: 5000 # 请求连接的超时时间
  OkToRetryOnAllOperations: true # 对所有操作请求都进行重试
  MaxAutoRetries: 2 # 对当前实例的重试次数
  MaxAutoRetriesNextServer: 2 # 切换实例的重试次数

logging:
  level:
    root: info