spring:
  application:
    name: server-sentinel
  cloud:
    sentinel:
      transport:
        client-ip: 10.168.1.193
        dashboard: 10.168.1.10:18080
    nacos:
      discovery:
        server-addr: 10.168.1.10:8848
feign:
  sentinel:
    enabled: true

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  ignored-services: '*'
  routes:
    provider:
      path: /provider/**
      serviceId: nacos-provider